apiVersion: v1
kind: Deployment
metadata:
  name: audio-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: audio-api
  template:
    metadata:
      labels:
        app: audio-api
    spec:
      containers:
      - name: audio-api
        image: abdoubasse/devops-audio-distribution:latest
        ports:
        - containerPort: 8000
