global:
  scrape_interval: 5s        # Intervalle de collecte des métriques
  evaluation_interval: 5s    # Intervalle d’évaluation des règles

scrape_configs:
  - job_name: 'audio_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']   # Nom du service API défini dans docker-compose

rule_files:
  - "alerts.yml"               # Fichier des règles d’alerte (optionnel)
